# Generated by Django 6.0.2 on 2026-02-15 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaccess',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentaccess',
            name='subject_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_access_rules', to='auth.group'),
        ),
        migrations.AddField(
            model_name='documentaccess',
            name='subject_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_access_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfeatureoverride',
            name='feature_flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='access_control.featureflag'),
        ),
        migrations.AddField(
            model_name='userfeatureoverride',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='documentaccess',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('subject_group__isnull', True), ('subject_user__isnull', False)), models.Q(('subject_group__isnull', False), ('subject_user__isnull', True)), _connector='OR'), name='exactly_one_document_access_subject'),
        ),
        migrations.AddConstraint(
            model_name='userfeatureoverride',
            constraint=models.UniqueConstraint(fields=('user', 'feature_flag'), name='uniq_user_feature_override'),
        ),
    ]
