# Generated by Django 6.0.2 on 2026-02-15 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '0002_document_project_hub'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='documentaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('subject_user__isnull', False)), fields=('document', 'subject_user', 'role'), name='uniq_document_user_role_access'),
        ),
        migrations.AddConstraint(
            model_name='documentaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('subject_group__isnull', False)), fields=('document', 'subject_group', 'role'), name='uniq_document_group_role_access'),
        ),
    ]
