# Generated by Django 6.0.2 on 2026-02-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_project_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
