# Generated by Django 6.0.2 on 2026-02-15 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_hubs', '0001_initial'),
        ('storage_backends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagebackend',
            name='project_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_backends', to='project_hubs.projecthub'),
        ),
    ]
